version: '3.7'

services:
  app:
    image: trending-api
    container_name: trending-api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:3000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379